apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: todo-app
        image: minageorge17/todo-list-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongodb-url
